### ISSUE TITLE
dmx devices with fixed values

### ISSUE THREAD

**Issue by bauersimon** [bauersimon/ScreenToArtNet#5]
# Summary
Some devices will require channels to be always-on (e.g. dimmer channel). This should be supported in the configuration.

# Tasks
- [x] figure out configuration and internal handling of "static" channels
- [x] implement in the dmx handler
  - [x] move artnet handling to it's own file
  - [x] add static section for the devices
