### ISSUE TITLE
nicer configuration structure

### ISSUE THREAD

**Issue by bauersimon** [bauersimon/ScreenToArtNet#7]
# Summary
The configuration structure is currently very limited. Would be nice to have a better structured configuration with less "implied" syntax.

# Tasks
- [x] figure out better configuration structure
- [x] move the devices into universes
- [x] implement into the tool
